spring:
  datasource:
    url: jdbc:mysql://db:3306/mydb?createDatabaseIfNotExist=true
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate # update x <- Flyway가 스키마 관리하도록 설정
    open-in-view: false
  # security:
  #   user:
  #     name: admin
  #     password: password
  #     roles: ADMIN
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
  jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION}
  auth:
    username: ${AUTH_USERNAME}
    password: ${AUTH_PASSWORD}