spring:
  datasource:
    url: jdbc:mysql://db:3306/mydb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  security:
    user:
      name: admin
      password: password
      roles: ADMIN
